// ============================================================
// EduAllocPro — Mock Data for Development
// All API calls fall back to this data when backend is unavailable.
// school_id is always STRING (11-digit UDISE code).
// ============================================================

export const MOCK_SCHOOLS = [
  {
    school_id: '27310100101',
    name: 'Zilla Parishad Primary School, Nandurbar',
    block: 'Nandurbar',
    cluster: 'Nandurbar Urban',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Primary',
    management: 'Government',
    lat: 21.3661,
    lng: 74.2167,
    di_score: 87,
    di_factors: ['Missing separate girls toilet', 'PTR > 40:1', 'No electricity connection'],
    enrollment_total: 142,
    enrollment_boys: 74,
    enrollment_girls: 68,
    enrollment_trend: [-5, -3, 2, -8, -4, 4],
    vacancies: [
      { subject: 'Mathematics', grade_range: '6-8', count: 2 },
      { subject: 'Science', grade_range: '6-8', count: 1 },
    ],
    total_vacancies: 3,
    rte_compliant: false,
    toilet_available: false,
    electricity_available: true,
    classroom_ratio: 0.62,
    urban_distance_km: 2.1,
    stu_tea_ratio: 48,
    udise_updated_at: '2023-03-15',
    is_data_stale: true,
    data_age_months: 14,
    di_breakdown: {
      stu_tea_ratio:    0.92,
      subject_vacancy:  0.85,
      toilet:           1.00,
      electricity:      0.30,
      classroom_ratio:  0.78,
      urban_distance:   0.20,
      enrollment_trend: 0.65,
      aser_proxy:       0.70,
    },
  },
  {
    school_id: '27310100202',
    name: 'Government High School, Shahada',
    block: 'Shahada',
    cluster: 'Shahada Rural',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Secondary',
    management: 'Government',
    lat: 21.5442,
    lng: 74.4693,
    di_score: 74,
    enrollment_total: 218,
    enrollment_boys: 112,
    enrollment_girls: 106,
    enrollment_trend: [10, -2, 5, 8, -3, 6],
    vacancies: [
      { subject: 'English', grade_range: '8-10', count: 1 },
      { subject: 'History', grade_range: '8-10', count: 1 },
    ],
    total_vacancies: 2,
    rte_compliant: true,
    toilet_available: true,
    electricity_available: true,
    classroom_ratio: 0.81,
    urban_distance_km: 8.4,
    stu_tea_ratio: 35,
    udise_updated_at: '2023-06-20',
    is_data_stale: true,
    data_age_months: 11,
    di_breakdown: {
      stu_tea_ratio:    0.65,
      subject_vacancy:  0.70,
      toilet:           0.00,
      electricity:      0.00,
      classroom_ratio:  0.40,
      urban_distance:   0.55,
      enrollment_trend: 0.30,
      aser_proxy:       0.60,
    },
  },
  {
    school_id: '27310100303',
    name: 'ZP School Taloda',
    block: 'Taloda',
    cluster: 'Taloda Block',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Primary',
    management: 'Government',
    lat: 21.5600,
    lng: 74.2100,
    di_score: 61,
    enrollment_total: 89,
    enrollment_boys: 45,
    enrollment_girls: 44,
    enrollment_trend: [2, 4, -1, 3, 5, 2],
    vacancies: [
      { subject: 'Mathematics', grade_range: '5-7', count: 1 },
    ],
    total_vacancies: 1,
    rte_compliant: true,
    toilet_available: true,
    electricity_available: false,
    classroom_ratio: 0.90,
    urban_distance_km: 15.2,
    stu_tea_ratio: 28,
    udise_updated_at: '2023-09-10',
    is_data_stale: false,
    data_age_months: 8,
    di_breakdown: {
      stu_tea_ratio:    0.50,
      subject_vacancy:  0.55,
      toilet:           0.00,
      electricity:      0.80,
      classroom_ratio:  0.20,
      urban_distance:   0.70,
      enrollment_trend: 0.20,
      aser_proxy:       0.50,
    },
  },
  {
    school_id: '27310100404',
    name: 'Ashram School Akkalkuwa',
    block: 'Akkalkuwa',
    cluster: 'Akkalkuwa Tribal',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Ashram',
    management: 'Government',
    lat: 21.5200,
    lng: 74.0100,
    di_score: 93,
    enrollment_total: 312,
    enrollment_boys: 158,
    enrollment_girls: 154,
    enrollment_trend: [-12, -8, -5, -10, -6, -3],
    vacancies: [
      { subject: 'Science', grade_range: '6-10', count: 3 },
      { subject: 'Mathematics', grade_range: '6-10', count: 2 },
      { subject: 'English', grade_range: '6-10', count: 2 },
    ],
    total_vacancies: 7,
    rte_compliant: false,
    toilet_available: false,
    electricity_available: false,
    classroom_ratio: 0.45,
    urban_distance_km: 42.0,
    stu_tea_ratio: 62,
    udise_updated_at: '2022-12-01',
    is_data_stale: true,
    data_age_months: 17,
    di_breakdown: {
      stu_tea_ratio:    1.00,
      subject_vacancy:  1.00,
      toilet:           1.00,
      electricity:      1.00,
      classroom_ratio:  1.00,
      urban_distance:   0.90,
      enrollment_trend: 0.95,
      aser_proxy:       0.90,
    },
  },
  {
    school_id: '27310100505',
    name: 'ZP Upper Primary School, Dhadgaon',
    block: 'Dhadgaon',
    cluster: 'Dhadgaon Rural',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Upper Primary',
    management: 'Government',
    lat: 21.7800,
    lng: 74.2500,
    di_score: 45,
    enrollment_total: 176,
    enrollment_boys: 90,
    enrollment_girls: 86,
    enrollment_trend: [5, 8, 3, 6, 4, 7],
    vacancies: [
      { subject: 'Hindi', grade_range: '6-8', count: 1 },
    ],
    total_vacancies: 1,
    rte_compliant: true,
    toilet_available: true,
    electricity_available: true,
    classroom_ratio: 0.95,
    urban_distance_km: 22.5,
    stu_tea_ratio: 25,
    udise_updated_at: '2024-01-15',
    is_data_stale: false,
    data_age_months: 4,
    di_breakdown: {
      stu_tea_ratio:    0.35,
      subject_vacancy:  0.30,
      toilet:           0.00,
      electricity:      0.00,
      classroom_ratio:  0.10,
      urban_distance:   0.60,
      enrollment_trend: 0.10,
      aser_proxy:       0.40,
    },
  },
  {
    school_id: '27310100606',
    name: 'Government Primary School, Nawapur',
    block: 'Nawapur',
    cluster: 'Nawapur Block',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Primary',
    management: 'Government',
    lat: 21.1500,
    lng: 73.8000,
    di_score: 28,
    enrollment_total: 95,
    enrollment_boys: 48,
    enrollment_girls: 47,
    enrollment_trend: [3, 5, 2, 4, 6, 3],
    vacancies: [],
    total_vacancies: 0,
    rte_compliant: true,
    toilet_available: true,
    electricity_available: true,
    classroom_ratio: 1.0,
    urban_distance_km: 5.2,
    stu_tea_ratio: 22,
    udise_updated_at: '2024-02-20',
    is_data_stale: false,
    data_age_months: 3,
    di_breakdown: {
      stu_tea_ratio:    0.20,
      subject_vacancy:  0.00,
      toilet:           0.00,
      electricity:      0.00,
      classroom_ratio:  0.00,
      urban_distance:   0.25,
      enrollment_trend: 0.05,
      aser_proxy:       0.30,
    },
  },
  {
    school_id: '27310100707',
    name: 'ZP School Molgi',
    block: 'Akkalkuwa',
    cluster: 'Molgi Cluster',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Marathi',
    category: 'Primary',
    management: 'Government',
    lat: 21.4800,
    lng: 73.9500,
    di_score: 82,
    enrollment_total: 67,
    enrollment_boys: 34,
    enrollment_girls: 33,
    enrollment_trend: [-8, -5, -3, -7, -4, -2],
    vacancies: [
      { subject: 'Mathematics', grade_range: '1-5', count: 1 },
      { subject: 'Marathi', grade_range: '1-5', count: 1 },
    ],
    total_vacancies: 2,
    rte_compliant: false,
    toilet_available: false,
    electricity_available: false,
    classroom_ratio: 0.55,
    urban_distance_km: 38.0,
    stu_tea_ratio: 45,
    udise_updated_at: '2023-01-10',
    is_data_stale: true,
    data_age_months: 16,
    di_breakdown: {
      stu_tea_ratio:    0.88,
      subject_vacancy:  0.80,
      toilet:           1.00,
      electricity:      1.00,
      classroom_ratio:  0.90,
      urban_distance:   0.85,
      enrollment_trend: 0.80,
      aser_proxy:       0.75,
    },
  },
  {
    school_id: '27310100808',
    name: 'Government High School, Nandurbar City',
    block: 'Nandurbar',
    cluster: 'Nandurbar Urban',
    district_code: 'NDB01',
    district_name: 'Nandurbar',
    medium: 'Semi-English',
    category: 'Secondary',
    management: 'Government',
    lat: 21.3750,
    lng: 74.2300,
    di_score: 38,
    enrollment_total: 445,
    enrollment_boys: 228,
    enrollment_girls: 217,
    enrollment_trend: [12, 8, 15, 10, 9, 14],
    vacancies: [
      { subject: 'Physics', grade_range: '11-12', count: 1 },
    ],
    total_vacancies: 1,
    rte_compliant: true,
    toilet_available: true,
    electricity_available: true,
    classroom_ratio: 1.1,
    urban_distance_km: 0.5,
    stu_tea_ratio: 30,
    udise_updated_at: '2024-03-01',
    is_data_stale: false,
    data_age_months: 2,
    di_breakdown: {
      stu_tea_ratio:    0.30,
      subject_vacancy:  0.20,
      toilet:           0.00,
      electricity:      0.00,
      classroom_ratio:  0.00,
      urban_distance:   0.05,
      enrollment_trend: 0.00,
      aser_proxy:       0.25,
    },
  },
]

export const MOCK_TEACHERS = [
  {
    teacher_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    name: 'Rajesh Kumar Patil',
    employee_id: 'MH-NDB-2847',
    subject_specialization: ['Mathematics', 'Science'],
    qualification: 'MSc BEd',
    years_experience: 8,
    years_rural: 3,
    current_district: 'Nashik',
    current_school_id: null,
    languages: ['mr', 'hi', 'en'],
    long_dist_consent: false,
    is_synthetic: true,
    lat: 20.0059,
    lng: 73.7898,
    match_score: 88,
    retention_score: 72,
    dvs: 0.81,
  },
  {
    teacher_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    name: 'Sunita Ramesh Desai',
    employee_id: 'MH-NDB-3102',
    subject_specialization: ['Mathematics', 'Physics'],
    qualification: 'BSc BEd',
    years_experience: 5,
    years_rural: 5,
    current_district: 'Dhule',
    current_school_id: null,
    languages: ['mr', 'hi'],
    long_dist_consent: true,
    is_synthetic: true,
    lat: 20.9042,
    lng: 74.7749,
    match_score: 82,
    retention_score: 85,
    dvs: 0.78,
  },
  {
    teacher_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    name: 'Pradeep Vishnu Jadhav',
    employee_id: 'MH-NDB-1956',
    subject_specialization: ['Science', 'Biology'],
    qualification: 'MSc BEd',
    years_experience: 12,
    years_rural: 7,
    current_district: 'Nandurbar',
    current_school_id: '27310100606',
    languages: ['mr', 'hi', 'en'],
    long_dist_consent: false,
    is_synthetic: true,
    lat: 21.1500,
    lng: 73.8000,
    match_score: 91,
    retention_score: 78,
    dvs: 0.85,
  },
  {
    teacher_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    name: 'Meena Suresh Bhosale',
    employee_id: 'MH-NDB-4231',
    subject_specialization: ['English', 'History'],
    qualification: 'MA BEd',
    years_experience: 6,
    years_rural: 2,
    current_district: 'Pune',
    current_school_id: null,
    languages: ['mr', 'en'],
    long_dist_consent: false,
    is_synthetic: true,
    lat: 18.5204,
    lng: 73.8567,
    match_score: 75,
    retention_score: 60,
    dvs: 0.71,
  },
  {
    teacher_id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    name: 'Anil Dattatray Shinde',
    employee_id: 'MH-NDB-2019',
    subject_specialization: ['Hindi', 'Marathi'],
    qualification: 'MA BEd',
    years_experience: 9,
    years_rural: 6,
    current_district: 'Nandurbar',
    current_school_id: null,
    languages: ['mr', 'hi'],
    long_dist_consent: true,
    is_synthetic: true,
    lat: 21.3661,
    lng: 74.2167,
    match_score: 79,
    retention_score: 88,
    dvs: 0.76,
  },
]

export const MOCK_TEACHER_MATCHES = [
  {
    rank: 1,
    teacher: MOCK_TEACHERS[0],
    di_score: 87,
    match_score: 88,
    retention_score: 72,
    dvs: 0.81,
    commute_km: 45.2,
    deployment_id: null,
    status: 'pending',
  },
  {
    rank: 2,
    teacher: MOCK_TEACHERS[1],
    di_score: 87,
    match_score: 82,
    retention_score: 85,
    dvs: 0.78,
    commute_km: 62.8,
    deployment_id: null,
    status: 'pending',
  },
  {
    rank: 3,
    teacher: MOCK_TEACHERS[2],
    di_score: 87,
    match_score: 91,
    retention_score: 78,
    dvs: 0.85,
    commute_km: 28.4,
    deployment_id: null,
    status: 'pending',
  },
  {
    rank: 4,
    teacher: MOCK_TEACHERS[3],
    di_score: 87,
    match_score: 75,
    retention_score: 60,
    dvs: 0.71,
    commute_km: 78.1,
    deployment_id: null,
    status: 'pending',
  },
  {
    rank: 5,
    teacher: MOCK_TEACHERS[4],
    di_score: 87,
    match_score: 79,
    retention_score: 88,
    dvs: 0.76,
    commute_km: 12.3,
    deployment_id: null,
    status: 'pending',
  },
]

export const MOCK_ASSIGNMENTS = [
  {
    assignment_id: 'asgn-001',
    school_id: '27310100101',
    school_name: 'ZP Primary School, Nandurbar',
    teacher_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    teacher_name: 'Rajesh Kumar Patil',
    subject: 'Mathematics',
    dvs: 0.81,
    commute_km: 45.2,
    status: 'approved',
  },
  {
    assignment_id: 'asgn-002',
    school_id: '27310100404',
    school_name: 'Ashram School Akkalkuwa',
    teacher_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    teacher_name: 'Sunita Ramesh Desai',
    subject: 'Science',
    dvs: 0.78,
    commute_km: 62.8,
    status: 'pending',
  },
  {
    assignment_id: 'asgn-003',
    school_id: '27310100404',
    school_name: 'Ashram School Akkalkuwa',
    teacher_id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    teacher_name: 'Pradeep Vishnu Jadhav',
    subject: 'Mathematics',
    dvs: 0.85,
    commute_km: 28.4,
    status: 'pending',
  },
  {
    assignment_id: 'asgn-004',
    school_id: '27310100202',
    school_name: 'Government High School, Shahada',
    teacher_id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
    teacher_name: 'Meena Suresh Bhosale',
    subject: 'English',
    dvs: 0.71,
    commute_km: 78.1,
    status: 'pending',
  },
  {
    assignment_id: 'asgn-005',
    school_id: '27310100505',
    school_name: 'ZP Upper Primary School, Dhadgaon',
    teacher_id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
    teacher_name: 'Anil Dattatray Shinde',
    subject: 'Hindi',
    dvs: 0.76,
    commute_km: 12.3,
    status: 'approved',
  },
]

export const MOCK_BRIEFING = {
  district_code: 'NDB01',
  district_name: 'Nandurbar',
  generated_at: new Date().toISOString(),
  english_summary: `Nandurbar district faces critical teacher shortages across 4 schools with Deprivation Index scores above 80. The Ashram School in Akkalkuwa has the highest DI score of 93, with 7 vacant positions across Science, Mathematics, and English subjects. Immediate deployment action is recommended for 12 teachers across 6 priority schools. The OR-Tools optimizer has identified an optimal assignment plan that covers 85% of critical vacancies while respecting the 80km commute constraint. Three schools lack basic toilet facilities, requiring infrastructure intervention alongside teacher deployment.`,
  marathi_summary: `नंदुरबार जिल्ह्यात 80 पेक्षा जास्त वंचितता निर्देशांक असलेल्या 4 शाळांमध्ये शिक्षकांची गंभीर कमतरता आहे. अक्कलकुव्यातील आश्रम शाळेचा सर्वाधिक DI गुण 93 आहे, विज्ञान, गणित आणि इंग्रजी विषयांमध्ये 7 रिक्त पदे आहेत. 6 प्राधान्य शाळांमध्ये 12 शिक्षकांसाठी तातडीने तैनाती कारवाई करण्याची शिफारस केली जाते. OR-Tools अनुकूलकाने 80 किमी प्रवास मर्यादेचा आदर करताना 85% गंभीर रिक्त पदे भरणारी इष्टतम नियुक्ती योजना ओळखली आहे.`,
  key_insights: [
    'Akkalkuwa block has 3 of the top 5 most deprived schools',
    'Science teacher shortage affects 68% of secondary schools',
    'Enrollment declining at 4 tribal ashram schools — intervention needed',
    'RTE PTR violations in 6 schools require immediate teacher deployment',
    '42% of UDISE data is older than 12 months — field verification recommended',
  ],
  urgent_actions: [
    { school_id: '27310100404', school_name: 'Ashram School Akkalkuwa', action: 'Deploy 3 Science teachers immediately', priority: 'critical' },
    { school_id: '27310100101', school_name: 'ZP Primary School, Nandurbar', action: 'Deploy Mathematics teacher + toilet construction', priority: 'critical' },
    { school_id: '27310100707', school_name: 'ZP School Molgi', action: 'Field verification + teacher deployment', priority: 'high' },
  ],
  total_vacancies: 14,
  critical_schools: 4,
  rte_violations: 6,
  schools_monitored: 8,
}

export const MOCK_STATS = {
  criticalSchools:  4,
  totalVacancies:   14,
  rteViolations:    6,
  schoolsMonitored: 8,
}
